/**
 * API endpoint catalog (service-oriented architecture).
 */
export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/login',
    REFRESH: '/api/refresh',
  },
  USER: {
    PRIVATE_PROFILE: '/api/private',
    CHANGE_PASSWORD: '/api/change-password',
    CHANGE_PASSWORD_INSTITUTIONAL: '/api/change-password-institutional',
  },
  SYSTEM: {
    PUBLIC_HEALTH: '/api/public',
  },
  GEOEXTRACTION: {
    GENERATE_SHAPEFILE: '/api/geoextraction/shapefiles',
    MERGE_SHAPEFILES: '/api/geoextraction/shapefiles/merges',
    CAPTURES: '/api/geoextraction/captures',
    CAPTURE: (id) => `/api/geoextraction/captures/${id}`,
    CAPTURE_IMAGE: (id) => `/api/geoextraction/captures/${id}/image`,
    CAPTURES_WS: '/api/geoextraction/captures/ws',
    CAPTURES_PRESENCE: '/api/geoextraction/captures/presence',
  },
  SECURITY: {
    ROLES: '/api/security/roles',
    ROLE_PERMISSIONS: (roleId) => `/api/security/roles/${roleId}/permissions`,
    ROLE: (roleId) => `/api/security/roles/${roleId}`,
    AREAS: '/api/security/areas',
    AREA: (areaId) => `/api/security/areas/${areaId}`,
    USERS: '/api/security/users',
    USER_ASSIGNMENT: (userId) => `/api/security/users/${userId}/assignment`,
    USER_STATUS: (userId) => `/api/security/users/${userId}/status`,
  },
  RESOLUTIONS: {
    BASE: '/api/resolutions',
    ONE: (id) => `/api/resolutions/${id}`,
    PAGE: (id, order) => `/api/resolutions/${id}/pages/${order}`,
    TABLE: (id) => `/api/resolutions/${id}/table`,
    PRESENCE: '/api/resolutions/presence',
    PLAN_PAGES: (id) => `/api/resolutions/${id}/plan-pages`,
    PLAN_PAGE: (id, order) => `/api/resolutions/${id}/plan-pages/${order}`,
    PLAN_PAGE_PLANTAS: (id, order) => `/api/resolutions/${id}/plan-pages/${order}/plantas`,
    PLAN_PAGE_DETECT: (id, order) => `/api/resolutions/${id}/plan-pages/${order}/detect-planta`,
  },
  FOLIOS: {
    BASE: '/api/folios',
    ONE: (id) => `/api/folios/${id}`,
    PAGE: (id, index, upright = true) => `/api/folios/${id}/pages/${index}?upright=${upright}`,
    DIAGNOSTICS: (id) => `/api/folios/${id}/diagnostics`,
    FILL_LOG: (id) => `/api/folios/${id}/fill-log`,
    REPROCESS: (id) => `/api/folios/${id}/reprocess`,
  },
  DETECTION: {
    HEALTH: '/api/detection/health',
    WMS_LAYERS: '/api/detection/wms/layers',
    DETECT_WMS: '/api/detection/jobs/detect-wms',
    PROGRESS: (jobId) => `/api/detection/jobs/${jobId}/progress`,
    RESULT: (jobId) => `/api/detection/jobs/${jobId}/result`,
    CANCEL: (jobId) => `/api/detection/jobs/${jobId}/cancel`,
    MANUAL_ALIGN: (jobId) => `/api/detection/jobs/${jobId}/manual-align`,
    MANUAL_ALIGN_PREVIEW: (jobId) => `/api/detection/jobs/${jobId}/manual-align/preview`,
    MANUAL_ALIGN_APPLY: (jobId) => `/api/detection/jobs/${jobId}/manual-align/apply`,
    CADASTRAL_RECORD: (id) => `/api/detection/cadastre/cadastral-record/${id}`,
    CAMPAIGNS: '/api/detection/campaigns',
    AFFECTED_PARCEL_REVIEW: (id) => `/api/detection/affected-parcels/${id}/review`,
    SECTORS: '/api/detection/sectors',
    SECTOR_DETAIL: (id) => `/api/detection/sectors/${id}`,
  },
  APPRAISAL_REVIEW: {
    PENDING: '/api/appraisal-review/appraisals',
    SEARCH: (formNumber) => `/api/appraisal-review/appraisals?form_number=${encodeURIComponent(formNumber)}`,
    DETAIL: (formNumber) => `/api/appraisal-review/appraisals/${encodeURIComponent(formNumber)}`,
    OBSERVATIONS: (formNumber) =>
      `/api/appraisal-review/appraisals/${encodeURIComponent(formNumber)}/observations`,
    MIGRATE: (formNumber) => `/api/appraisal-review/appraisals/${encodeURIComponent(formNumber)}/migrate`,
  },
  TEMPLATES: {
    BASE: '/api/templates',
    ONE: (id) => `/api/templates/${id}`,
    VARIABLES: '/api/templates/variables',
    CITES: '/api/templates/cites',
    CITES_CONFIGURACIONES: '/api/templates/cites/configuraciones',
    CITES_GENERAR: '/api/templates/cites/generar',
  },
  DIGITIZATION: {
    WORKERS: '/api/digitization/workers',
    STOP_WORKER: '/api/digitization/workers/stop',
  },
  FOLDER_ANALYSIS: {
    CATALOG: '/api/folder-analysis/catalog',
    CADASTRAL_PARCEL: '/api/folder-analysis/cadastral/parcel',
    CADASTRAL_CROQUIS: '/api/folder-analysis/cadastral/croquis',
    CAPTURES: '/api/folder-analysis/captures',
    CAPTURE: (id) => `/api/folder-analysis/captures/${id}`,
    CAPTURE_IMAGE: (id) => `/api/folder-analysis/captures/${id}/image`,
    CAPTURE_PREVIEW: (id) => `/api/folder-analysis/captures/${id}/preview`,
    CAPTURE_THUMBNAIL: (id) => `/api/folder-analysis/captures/${id}/thumbnail`,
    // Indicador "Celular conectado". Se consulta por REST (no hay websocket en
    // este modulo) y el backend lo responde desde Postgres, asi que cualquiera
    // de los 4 workers da la misma respuesta.
    CAPTURES_PRESENCE: '/api/folder-analysis/captures/presence',
    DOCUMENTS: '/api/folder-analysis/documents',
    REVIEWED_DOCUMENTS: '/api/folder-analysis/documents/reviewed',
    DOCUMENT: (id) => `/api/folder-analysis/documents/${id}`,
    DOCUMENT_PAGES: (id) => `/api/folder-analysis/documents/${id}/pages`,
    DOCUMENT_ANALYZE: (id) => `/api/folder-analysis/documents/${id}/analyze`,
    DOCUMENT_REVIEW: (id) => `/api/folder-analysis/documents/${id}/review`,
    DOCUMENT_EXPORT: (id) => `/api/folder-analysis/documents/${id}/export`,
    FOLDERS: '/api/folder-analysis/folders',
    FOLDER: (id) => `/api/folder-analysis/folders/${id}`,
    FOLDER_DOCUMENTS: (id) => `/api/folder-analysis/folders/${id}/documents`,
    FOLDER_DOCUMENT: (id, documentId) => `/api/folder-analysis/folders/${id}/documents/${documentId}`,
  },
  REPORTS: {
    FILTERS: '/api/procedurereports/filters',
    REPORT: '/api/procedurereports/reports',
    EXPORT_EXCEL: '/api/procedurereports/reports/export/excel',
    EXPORT_PDF: '/api/procedurereports/reports/export/pdf',
  },
  CHATBOT: {
    CHAT: '/api/chatbot/chat',
    VISION: '/api/chatbot/vision',
    FEEDBACK: '/api/chatbot/feedback',
    PROCEDURES: '/api/chatbot/procedures',
    PROCEDURE: (code) => `/api/chatbot/procedures/${code}`,
    INGESTS: '/api/chatbot/ingests',
    REINDEX_EMBEDDINGS: '/api/chatbot/embeddings/reindex',
  },
  ALIGNMENT: {
    WMS_LAYERS: '/api/alignment/wms/layers',
    WMS_IMAGE: '/api/alignment/wms/image',
    BLOCKS: '/api/alignment/blocks',
    BLOCK: (id) => `/api/alignment/blocks/${id}`,
    BLOCK_CONFIRM: (id) => `/api/alignment/blocks/${id}/confirm`,
    COVERAGE: '/api/alignment/coverage',
  },
}
